# Generated by Django 3.2.7 on 2024-03-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
    ]
